# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Verb.create([
  { :name => "Ate", :hide_object => nil, :hide_price => nil, :hide_url => nil, :hide_people => nil, :created_at => "2013-01-26 20:45:46", :updated_at => "2013-02-12 10:30:14", :is_active => true, :sort_order => 1, :object_label => nil, :object_example => nil, :kind => nil },
  { :name => "Met", :hide_object => nil, :hide_price => true, :hide_url => nil, :hide_people => nil, :created_at => "2013-01-26 20:46:01", :updated_at => "2013-02-12 10:30:14", :is_active => true, :sort_order => nil, :object_label => nil, :object_example => nil, :kind => nil },
  { :name => "Attended", :hide_object => nil, :hide_price => nil, :hide_url => nil, :hide_people => nil, :created_at => "2013-01-26 20:46:16", :updated_at => "2013-02-12 10:30:15", :is_active => true, :sort_order => nil, :object_label => nil, :object_example => nil, :kind => nil },
  { :name => "Thought", :hide_object => nil, :hide_price => true, :hide_url => true, :hide_people => true, :created_at => "2013-01-26 20:46:04", :updated_at => "2013-02-12 10:30:15", :is_active => false, :sort_order => nil, :object_label => nil, :object_example => nil, :kind => nil },
  { :name => "Visited", :hide_object => true, :hide_price => true, :hide_url => nil, :hide_people => nil, :created_at => "2013-01-26 20:46:12", :updated_at => "2013-02-12 10:30:15", :is_active => true, :sort_order => nil, :object_label => nil, :object_example => nil, :kind => nil },
  { :name => "Wore", :hide_object => nil, :hide_price => true, :hide_url => nil, :hide_people => true, :created_at => "2013-01-26 20:46:24", :updated_at => "2013-02-12 10:30:15", :is_active => true, :sort_order => nil, :object_label => nil, :object_example => nil, :kind => nil },
  { :name => "Read", :hide_object => nil, :hide_price => true, :hide_url => nil, :hide_people => nil, :created_at => "2013-01-26 20:46:44", :updated_at => "2013-02-12 10:30:15", :is_active => true, :sort_order => nil, :object_label => nil, :object_example => nil, :kind => nil },
  { :name => "Watched", :hide_object => nil, :hide_price => nil, :hide_url => nil, :hide_people => nil, :created_at => "2013-01-26 20:46:41", :updated_at => "2013-02-12 10:30:15", :is_active => true, :sort_order => nil, :object_label => nil, :object_example => nil, :kind => nil },
  { :name => "Bought", :hide_object => nil, :hide_price => nil, :hide_url => nil, :hide_people => nil, :created_at => "2013-01-26 20:45:50", :updated_at => "2013-02-12 10:30:15", :is_active => true, :sort_order => nil, :object_label => nil, :object_example => nil, :kind => "THING" },
  { :name => "Had", :hide_object => nil, :hide_price => nil, :hide_url => nil, :hide_people => true, :created_at => "2013-01-26 20:45:53", :updated_at => "2013-02-12 10:30:15", :is_active => false, :sort_order => nil, :object_label => nil, :object_example => nil, :kind => "THING" },
  { :name => "Spent", :hide_object => nil, :hide_price => nil, :hide_url => true, :hide_people => true, :created_at => "2013-02-12 10:46:45", :updated_at => "2013-02-12 10:46:45", :is_active => true, :sort_order => nil, :object_label => nil, :object_example => nil, :kind => nil }
], :without_protection => true )


